### ISSUE TITLE
(Closeable)ThreadContext putAll removes entire context

### ISSUE THREAD

**Issue by nielsm5** [apache/logging-log4j2#2946] opened 2024-09-12 14:47 UTC
## Description

The ThreadContext no longer works as intended. The new version closes/removes items from the stack when it shouldn't.

CloseableThreadContext calls `ThreadContext.putAll`.
``` java
if (!valuesToReplace.isEmpty()) {
    ThreadContext.putAll(valuesToReplace);
}
```
Once putAll has been called, the stack is gone, and only the newly inserted values are present.
Since it's used by `CloseableThreadContext#close()` it's quite destructive...

## Configuration

**Version:** 2.24.0

**Operating system:** All

**JDK:** All

## Reproduction

```java
	@Test
	public void testAutoCloseableThreadContext() {
		try (final CloseableThreadContext.Instance ctc1 = CloseableThreadContext.put("outer", "one")) {
			try (final CloseableThreadContext.Instance ctc2 = CloseableThreadContext.put("outer", "two")) {
				assertEquals("two", ThreadContext.get("outer"));

				try (final CloseableThreadContext.Instance ctc3 = CloseableThreadContext.put("inner", "one")) {
					assertEquals("one", ThreadContext.get("inner"));

					ThreadContext.put("not-in-closeable", "true");
					assertEquals("two", ThreadContext.get("outer"));
				}

				assertEquals("two", ThreadContext.get("outer"));
				assertNull(ThreadContext.get("inner"));
			}

			assertEquals("one", ThreadContext.get("outer"));
			assertNull(ThreadContext.get("inner"));
		}
		assertEquals("true", ThreadContext.get("not-in-closeable"));

		assertNull(ThreadContext.get("inner"));
		assertNull(ThreadContext.get("outer"));
	}
```

and

```java
	@Test
	public void testAutoCloseableThreadContextPutAll() {
		try (final CloseableThreadContext.Instance ctc1 = CloseableThreadContext.put("outer", "one")) {
			try (final CloseableThreadContext.Instance ctc2 = CloseableThreadContext.put("outer", "two")) {
				assertEquals("two", ThreadContext.get("outer"));

				try (final CloseableThreadContext.Instance ctc3 = CloseableThreadContext.put("inner", "one")) {
					assertEquals("one", ThreadContext.get("inner"));

					ThreadContext.put("not-in-closeable", "true");
					ThreadContext.putAll(Collections.singletonMap("inner", "two"));
					assertEquals("two", ThreadContext.get("inner"));
					assertEquals("two", ThreadContext.get("outer"));
				}

				assertEquals("two", ThreadContext.get("outer"));
				assertNull(ThreadContext.get("inner"));
			}

			assertEquals("one", ThreadContext.get("outer"));
			assertNull(ThreadContext.get("inner"));
		}
		assertEquals("true", ThreadContext.get("not-in-closeable"));

		assertNull(ThreadContext.get("inner"));
		assertNull(ThreadContext.get("outer"));
	}
```

**Comment by tnleeuw** [comment] 2024-09-12 14:51
Another test that shows the same failure is this test, which does not use `ThreadContext.put` / `ThreadContext.putAll()` in the test code but just nesting of `CloseableThreadContext.Instance`, with nested values that need to be restored on closing an inner context:

```
	@Test
	public void testCloseableThreadContextWithMultipleNestingLevels() {
		ThreadContext.clearMap();

		try (CloseableThreadContext.Instance k1Outer = CloseableThreadContext.put("k1", "outer")) {
			assertEquals("outer", ThreadContext.get("k1"));
			try (CloseableThreadContext.Instance k1Inner = CloseableThreadContext.put("k1", "inner")) {
				assertEquals("inner", ThreadContext.get("k1"));

				try (CloseableThreadContext.Instance k2Outer = CloseableThreadContext.put("k2", "outer")) {
					assertEquals("inner", ThreadContext.get("k1"));
					assertEquals("outer", ThreadContext.get("k2"));
					try (CloseableThreadContext.Instance k2Inner = CloseableThreadContext.put("k2", "inner")) {
						assertEquals("inner", ThreadContext.get("k1"));
						assertEquals("inner", ThreadContext.get("k2"));

					}
					assertEquals("inner", ThreadContext.get("k1")); // Expect k1 to still exist but it has disappeared here
					assertEquals("outer", ThreadContext.get("k2"));
				}
				assertEquals("inner", ThreadContext.get("k1"));
				assertNull(ThreadContext.get("k2"));

			}
			assertEquals("outer", ThreadContext.get("k1"));
			assertNull(ThreadContext.get("k2"));
		}
		assertNull(ThreadContext.get("k1"));
	}
```

**Comment by ppkarwasz** [comment] 2024-09-12 15:03
@nielsm5,

Thank you for the report. I believe this is the same problem that was fixed in #2942.

**Comment by tnleeuw** [comment] 2024-09-12 15:10
> @nielsm5,
> 
> Thank you for the report. I believe this is the same problem that was fixed in #2942.

That would be great; does it fix the tests we added? (Just short on time to verify that myself right now but if you don't have time either then perhaps tomorrow I can find the time to verify this).

**Comment by ppkarwasz** [comment] 2024-09-12 16:34
@nielsm5,

Can you check the latest `2.24.1-SNAPSHOT` snapshot, if it solves the problem (see [Logging Services Download](https://logging.apache.org/download.html) for details about our snapshot repository).

**Comment by ppkarwasz** [comment] 2024-09-12 19:52
> That would be great; does it fix the tests we added? (Just short on time to verify that myself right now but if you don't have time either then perhaps tomorrow I can find the time to verify this).

I believe so, the problem with `putAll` was that it overwrote the previous entries instead of appending to them.

**Comment by tnleeuw** [comment] 2024-09-12 19:54
> > That would be great; does it fix the tests we added? (Just short on time to verify that myself right now but if you don't have time either then perhaps tomorrow I can find the time to verify this).
> 
> I believe so, the problem with `putAll` was that it overwrote the previous entries instead of appending to them.

Sounds like it should fix this issue. I will test with a snapshot-build tomorrow.

**Comment by tnleeuw** [comment] 2024-09-13 07:00
I can confirm that the latest snapshot build fixes our tests.

**Comment by ppkarwasz** [comment] 2024-09-13 07:10
Thanks for the confirmation, I am closing it and adding it to the `2.24.1` milestone due in about 10 days.

**Comment by nielsm5** [comment] 2024-09-30 09:43
This has NOT been fixed (yet).

**Comment by vy** [comment] 2024-09-30 11:22
@nielsm5, that is ~embarrassing~ sad, to say the least. :disappointed: Apologies for the inconvenience. Thanks for the report. I will take care of this issue in a day or two.

**Comment by nielsm5** [comment] 2024-09-30 11:30
Thanks, and no worries, mistakes happen. Luckily we've got tests.

**Comment by tnleeuw** [comment] 2024-09-30 11:32
I see now that perhaps 2 weeks ago there was a case that I did not verify when testing the snapshot.

Here are 2 unit tests that show the issue. These unit tests only use JDK apis, JUnit, and Log4J2 api.

While in the scope of the inner nested CloseableThreadContext, `ctc3`, a value is put directly into the ThreadContext with a key (`not-in-closeable`) that is not part of any of the CloseableThreadContexts. (This case was not in my earlier scenarios).

After the context `ctc3` is closed, the key `inner` that was added by `ctc3` should be removed but the assert shows that it isn't.


In Log4J2 2.23.1 this test passes.

```

	@Test
	public void testAutoCloseableThreadContext() {
		ThreadContext.clearMap();
		try (final CloseableThreadContext.Instance ctc1 = CloseableThreadContext.put("outer", "one")) {
			try (final CloseableThreadContext.Instance ctc2 = CloseableThreadContext.put("outer", "two")) {
				assertEquals("two", ThreadContext.get("outer"));

				try (final CloseableThreadContext.Instance ctc3 = CloseableThreadContext.put("inner", "one")) {
					assertEquals("one", ThreadContext.get("inner"));

					ThreadContext.put("not-in-closeable", "true");
					assertEquals("two", ThreadContext.get("outer"));
				}

				assertEquals("two", ThreadContext.get("outer"));
				assertNull(ThreadContext.get("inner"));
			}

			assertEquals("one", ThreadContext.get("outer"));
			assertNull(ThreadContext.get("inner"));
		}
		assertEquals("true", ThreadContext.get("not-in-closeable"));

		assertNull(ThreadContext.get("inner"));
		assertNull(ThreadContext.get("outer"));
	}

	@Test
	public void testAutoCloseableThreadContextPutAll() {
		ThreadContext.clearMap();
		try (final CloseableThreadContext.Instance ctc1 = CloseableThreadContext.put("outer", "one")) {
			try (final CloseableThreadContext.Instance ctc2 = CloseableThreadContext.put("outer", "two")) {
				assertEquals("two", ThreadContext.get("outer"));

				try (final CloseableThreadContext.Instance ctc3 = CloseableThreadContext.put("inner", "one")) {
					assertEquals("one", ThreadContext.get("inner"));

					ThreadContext.put("not-in-closeable", "true");
					ThreadContext.putAll(Collections.singletonMap("inner", "two"));
					System.err.println(ThreadContext.getContext());
					assertEquals("two", ThreadContext.get("inner"));
					assertEquals("two", ThreadContext.get("outer"));
				}

				assertEquals("two", ThreadContext.get("outer"));
				assertNull(ThreadContext.get("inner"));
			}

			assertEquals("one", ThreadContext.get("outer"));
			assertNull(ThreadContext.get("inner"));
		}
		assertEquals("true", ThreadContext.get("not-in-closeable"));

		assertNull(ThreadContext.get("inner"));
		assertNull(ThreadContext.get("outer"));
	}
```

**Comment by vy** [comment] 2024-10-03 10:49
@tnleeuw, @nielsm5, would you mind reviewing #3050, please?

**Comment by tnleeuw** [comment] 2024-10-03 11:06
> @tnleeuw, @nielsm5, would you mind reviewing #3050, please?

I am not sure about the actual changes to the map-updating as I don't know the code well enough but I see you included both test-cases provided above, so if they pass the changes should be good to go!

**Comment by vy** [comment] 2024-10-03 11:08
> I am not sure about the actual changes to the map-updating as I don't know the code well enough but I see you included both test-cases provided above, so if they pass the changes should be good to go!

@tnleeuw, could you locally compile that branch (see [`BUILDING.adoc`](https://github.com/apache/logging-log4j2/blob/2.x/BUILDING.adoc)) and use the produced artifacts to see if they pass _your tests_?

**Comment by tnleeuw** [comment] 2024-10-03 12:11
> > I am not sure about the actual changes to the map-updating as I don't know the code well enough but I see you included both test-cases provided above, so if they pass the changes should be good to go!
> 
> @tnleeuw, could you locally compile that branch (see [`BUILDING.adoc`](https://github.com/apache/logging-log4j2/blob/2.x/BUILDING.adoc)) and use the produced artifacts to see if they pass _your tests_?

I'm trying but I get weird errors in my project about classes not found, when I change my log4j2 dependency to 2.25.0-SNAPSHOT.
I do see that version in my local Maven repository.

I'm not quite sure what's going on, Maven doesn't give me a very sensible error message but IntelliJ complains about not being able to load the annotation class NullMarked from jspecify.

```
java: cannot access org.jspecify.annotations.NullMarked
  class file for org.jspecify.annotations.NullMarked not found
```

And from the Maven output:
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] cannot access org.jspecify.annotations.NullMarked
  class file for org.jspecify.annotations.NullMarked not found
```

This goes away again as soon as I switch back to any release version of Log4J2.

I'm a bit puzzled because git blame seems to indicate that jspecify has been part of the project for a long time already, and is not a transitive dependency of release versions of Log4J2 either.

**Comment by vy** [comment] 2024-10-03 12:40
@tnleeuw, if I understand it right, you are able to successfully compile Log4j, though using it in your project is failing due to the error you cited. I will further investigate the JSpecify issue. In the meantime, could you add JSpecify dependency in the `provided` scope (for the time being) and see if MDC behaves as expected, please?

**Comment by ppkarwasz** [comment] 2024-10-03 12:41
> I'm a bit puzzled because git blame seems to indicate that jspecify has been part of the project for a long time already, and is not a transitive dependency of release versions of Log4J2 either.

I am a bit puzzled too, since annotations were conceived from the start as **optional** and compilation should not fail if they are missing. Which JDK are you using to compile your project? There is a known bug in JDK 8 ([JDK-8152174](https://bugs.openjdk.org/browse/JDK-8152174)) that causes problem if optional annotations are missing.

**Comment by tnleeuw** [comment] 2024-10-03 12:41
Adding jspecify to my own dependencies, tests that previously failed do now succeed. Still running the entire test suite.

**Comment by tnleeuw** [comment] 2024-10-03 12:49
> > I'm a bit puzzled because git blame seems to indicate that jspecify has been part of the project for a long time already, and is not a transitive dependency of release versions of Log4J2 either.
> 
> I am a bit puzzled too, since annotations were conceived from the start as **optional** and compilation should not fail if they are missing. Which JDK are you using to compile your project? There is a known bug in JDK 8 ([JDK-8152174](https://bugs.openjdk.org/browse/JDK-8152174)) that causes problem if optional annotations are missing.

I currently use JDK17.0.12, built by Amazon.
There's no problem with other builds, which also use jspecify annotations, so that puzzles me. The only difference might be that I built this version locally from IntelliJ, letting IntelliJ build the commandline:

```
C:\Users\Tim\.jdks\corretto-17.0.12\bin\java.exe -Dmaven.multiModuleProjectDirectory=C:\Users\Tim\IdeaProjects\logging-log4j2 [lots of paths and OPENS added by IntelliJ] org.codehaus.classworlds.Launcher -Didea.version=2024.2.3 -DskipTests=true install
```

Using Maven 3.9.8 from the Maven wrapper

**Comment by vy** [comment] 2024-10-03 12:51
> I built this version locally from IntelliJ

@tnleeuw, just to get the most obvious probability out of our way, could you try the following instead, please?

```
./mvnw clean install -DskipTests
```

**Comment by tnleeuw** [comment] 2024-10-03 13:08
> > I built this version locally from IntelliJ
> 
> @tnleeuw, just to get the most obvious probability out of our way, could you try the following instead, please?
> 
> ```
> ./mvnw clean install -DskipTests
> ```

Done but that doesn't make any difference.

Again using Amazon Coretto JDK 17.0.12 to build Log4J2, and also for my project.

**Comment by tnleeuw** [comment] 2024-10-03 13:28
When I add jspecify as dependency to my project, all LogContext / ThreadContext related tests pass.

There is 1 failing test, which is an unexpected newline at the end of a logline. That doesn't look related to anything to do with the ThreadContext but it's something for ourselves to keep in mind after the release of 2.25.0.

**Comment by vy** [comment] 2024-10-03 13:41
@tnleeuw, thank you so much for taking to time the evaluate the fix! :heart_eyes: Much appreciated! :bow:

> When I add jspecify as dependency to my project, all LogContext / ThreadContext related tests pass.
> 
> There is 1 failing test, which is an unexpected newline at the end of a logline. That doesn't look related to anything to do with the ThreadContext but it's something for ourselves to keep in mind after the release of 2.25.0.

`2.25.0` will ship a written-from-scratch exception rendering logic for Pattern Layout – #2691. (We will ofcourse document this in release notes.) Could you check if the discrepancy is due to a usage of `%ex`, `%xEx`, or `%xEx`, please?

**Comment by tnleeuw** [comment] 2024-10-03 15:25
> @tnleeuw, thank you so much for taking to time the evaluate the fix! 😍 Much appreciated! 🙇
> 
You're welcome!

> > When I add jspecify as dependency to my project, all LogContext / ThreadContext related tests pass.
> > There is 1 failing test, which is an unexpected newline at the end of a logline. That doesn't look related to anything to do with the ThreadContext but it's something for ourselves to keep in mind after the release of 2.25.0.
> 
> `2.25.0` will ship a written-from-scratch exception rendering logic for Pattern Layout – #2691. (We will ofcourse document this in release notes.) Could you check if the discrepancy is due to a usage of `%ex`, `%xEx`, or `%xEx`, please?

The code uses a custom TestAppender class and a custom Layout class that extends from `AbstractStringLayout` and has a `PatternFormatter[]` parsed from this pattern: `"%level - %m - %throwable{1}"`

So as far as I can determine from our custom log4j code, we do not use any of `%ex`, `%xEx`, or `%xEx` -- unless I miss something that happens underwater.

**Comment by ppkarwasz** [comment] 2024-10-07 09:58
@nielsm5,

Could you explain your use-case for the following assertion on the "not-in-closeable" key:

```java
ThreadContext.clearMap();
try (final CloseableThreadContext.Instance c = CloseableThreadContext.put("inner", "one")) {
    ThreadContext.put("not-in-closeable", "true");
}
assertEquals("true", ThreadContext.get("not-in-closeable"));
```

The `CloseableThreadContext` contract does not specify _how_ the original thread context must be restored, but only that it must be restored. So whether the "not-in-closeable" key is kept or restore to the original value is IMHO implementation specific.

**Comment by tnleeuw** [comment] 2024-10-07 10:03
@ppkarwasz This is not a complete answer to your question but see my comment that I just added to the PR: https://github.com/apache/logging-log4j2/pull/3050#discussion_r1789912608

**Comment by vy** [comment] 2024-10-07 10:46
> this pattern: `"%level - %m - %throwable{1}"`

`%throwable`, `%ex`, `%exception` are all synonyms referring to the same [exception pattern converter](https://logging.apache.org/log4j/2.x/manual/pattern-layout.html#converter-exception). Starting with `2.25.0`, exception handling will have some _behavioral_ changes. In your particular case, `%level - %m - %throwable{1}` outputs

* `<2.25.0` :arrow_right: `INFO - hello world - first line of stack trace\n`
* `>=2.25.0` :arrow_right: `INFO - hello world - \nfirst line of stack trace\n`
  * Note the newline prefix before the 1st stack trace line
  * Will be introduced with #3045

**Comment by tnleeuw** [comment] 2024-10-07 10:55
> > this pattern: `"%level - %m - %throwable{1}"`
> 
> @tnleeuw, `%throwable`, `%ex`, `%exception` are all synonyms referring to the same [exception pattern converter](https://logging.apache.org/log4j/2.x/manual/pattern-layout.html#converter-exception). Starting with `2.25.0`, exception handling will have some _behavioral_ changes. In your particular case, `%level - %m - %throwable{1}` outputs

I didn't even realize `%ex` was short for `%exception` and synonymous with `%throwable` -- makes sense of course, but I just didn't think of it when looking at it last week! 😳 
Anyway this change is not consequential for us, we just need to be aware, and probably just add a `.trim()` to our test.

**Comment by nielsm5** [comment] 2024-10-07 11:40
> @nielsm5,
> 
> Could you explain your use-case for the following assertion on the "not-in-closeable" key:
> 
> ```java
> ThreadContext.clearMap();
> try (final CloseableThreadContext.Instance c = CloseableThreadContext.put("inner", "one")) {
>     ThreadContext.put("not-in-closeable", "true");
> }
> assertEquals("true", ThreadContext.get("not-in-closeable"));
> ```
> 
> The `CloseableThreadContext` contract does not specify _how_ the original thread context must be restored, but only that it must be restored. So whether the "not-in-closeable" key is kept or restore to the original value is IMHO implementation specific.

I hear you, however this is how it's always worked up to version 24. I would expect this behavior to keep working as-is without Log4j2 suddenly introducing non-backwards-compatible/breaking changes.

**Comment by ppkarwasz** [comment] 2024-10-08 10:15
> @sjoerdtalsma @Marcono1234 If you see this message, I am under the impression that your system also depends on Log4J2 ThreadContext behaviour as it was until Log4J2 2.23.1. Since the Log4J team is trying to understand if we genuinely have need / use-case for that behaviour, I would appreciate to hear what is your use-case and what breaks with the current Log4J 2.24.1 behaviour.

To be more precise the behavior in `2.24.0` and `2.24.1` is a bug in the `ThreadContext.remove()` and `ThreadContext.removeAll()` methods. We will address it **regardless** of this discussion.

What we are discussing here is the future of the Log4j API. @rgoers, plans to introduce a new tool called `ScopedContext`, which will work like this:

```java
ScopedContext.where("foo", "bar").run(() -> some lambda);
```

This API will clear all the changes to the context data of the current thread once "some lambda" exits. You will be even allowed to add custom `Object`s to the context data or maps that will be converted to JSON, without the risk of memory leaks.

Once that is out, we think about deprecating `ThreadContext`. As far as I understand, this will break your use-case.

**Comment by tnleeuw** [comment] 2024-10-08 10:57
If there is a way to get from current scope to outer scope, or root scope, then we can "walk that tree" and put things in the outer scope -- which will eventually be cleared, after the top-level process that runs on the thread exits.
That way there could be a structured way to propagate information up the log-context scope that we now wish to see in the log-context for the remainder of a process-execution.

I don't know what others in my team think about it.

**Comment by sjoerdtalsma** [comment] 2024-10-08 18:25
> @sjoerdtalsma @Marcono1234 If you see this message, I am under the impression that your system also depends on Log4J2 ThreadContext behaviour as it was until Log4J2 2.23.1. Since the Log4J team is trying to understand if we genuinely have need / use-case for that behaviour, I would appreciate to hear what is your use-case and what breaks with the current Log4J 2.24.1 behaviour.

Hi, thanks for touching base.

Let me try to explain our use-case.

The puropose of our framework is propagating a snapshot consisting of one or more threadlocal states to a new thread.
For this we provide context-aware implementations of Runnable, Callable, CompletableFuture, ExecutorService, etc.
The framework is pluggable, meaning it will detect ContextManager implementations automatically to be included in the snapshot. On such ContextManager implementation for Log4J2 intends to propagate the logging context from the current thread to the snapshot.

The features our framework needs are:
- capturing the state from the current thread
- (temporarily) reactivating this state on another thread, ideally restoring the state to what it was before reactivating the snapshot by closing the reactivation.

I hope this makes some sense? Feel free to reach out if further questions exist.

**Comment by Marcono1234** [comment] 2024-10-08 23:12
I hadn't investigated in depth why https://github.com/talsma-ict/context-propagation/pull/484 respectively https://github.com/talsma-ict/context-propagation/pull/491 failed; based on the Log4j 2 release notes I had assumed it is related to this issue here and suggested to wait for the fix.

But now after having looked a bit into this, it seems the failures might not be related to the issue here. Sorry for the confusion.

Instead #2374 seems to have caused a behavior change: In 2.23.1 and before it seems `NoOpThreadContextMap` was only used if the thread context map was [explicitly disabled](https://github.com/apache/logging-log4j2/blob/rel/2.23.1/log4j-api/src/main/java/org/apache/logging/log4j/ThreadContext.java#L219-L221). Otherwise, even if no Log4j provider was found, a [functional thread context map was used](https://github.com/apache/logging-log4j2/blob/rel/2.23.1/log4j-api/src/main/java/org/apache/logging/log4j/spi/ThreadContextMapFactory.java#L139-L147).
With the changes from #2374 if no provider is present, `SimpleProvider` is used and that uses `NoOpThreadContextMap` by default.

However, I am not sure if that has any noticeable effect on production applications because they most likely have a Log4j 2 provider on their classpath (probably log4j-core), or if not they are not using or don't care if `ThreadContext` is functional or not.

It was just the case that https://github.com/talsma-ict/context-propagation previously only had a log4j-api dependency, but was using `ThreadContext` in the unit tests and was expecting that it works (because talsma-ict/context-propagation is a library with integration for Log4j 2, but it does not actually use Log4j 2 for logging). The solution seems to be to simply add log4j-core as `test` scoped dependency, see https://github.com/talsma-ict/context-propagation/pull/498.

**Comment by tnleeuw** [comment] 2024-10-09 05:59
@sjoerdtalsma @Marcono1234 Thanks for getting back to us! We also do have some code that copies state from one thread to another including the Log4J2 ThreadContext, but at least as of 2.24.1 that part does not break.
For the rest it seems that our use-cases do not overlap.

**Closed** 2024-10-10 11:46 UTC
Labels: bug, api, waiting-for-maintainer
