### ISSUE TITLE
2.24.0 status logger warns about message factory mismatch

### ISSUE THREAD

**Issue by arlampin** [apache/logging-log4j2#2933] opened 2024-09-09 12:26 UTC
## Description

After updating to 2.24.0 from 2.23.1, the status logger logs the following warning:

```
2024-09-09T12:14:29.525247Z main WARN The Logger eu.lampinen.log4j2test.Test was created with the message factory org.apache.logging.log4j.message.ReusableMessageFactory@3d680b5a and is now requested with a null message factory (defaults to org.apache.logging.log4j.message.ParameterizedMessageFactory), which may create log events with unexpected formatting.
```

The whole sample code is below

```java

import org.apache.logging.log4j.LogManager;

public class Test {

    static {
        System.setProperty("log4j2.statusLoggerLevel", "WARN");
    }

    public static void main(String[] args) {
        LogManager.getLogger(Test.class).error("Hello {}", "world!");
        LogManager.getLogger(Test.class).error("Hello {}", "world!");
    }

}
```

I think this is caused by a mismatch between
* `AbstractLogger.checkMessageFactory`, which uses constant `DEFAULT_MESSAGE_FACTORY_CLASS`
* `Logger.getEffectiveMessageFactory`, which uses either `ReusableMessageFactory` or `ParameterizedMessageFactory` depending on `Constants.ENABLE_THREADLOCALS`.

Setting `log4j2.enable.threadlocals=false` will disable the warning.

## Configuration

**Version:** 2.24.0

**JDK:** Azul 21

## Logs

2.23.1
```
ERROR - Hello world!
ERROR - Hello world!
```

2.24.0
```
ERROR - Hello world!
2024-09-09T12:16:29.792995Z main WARN The Logger eu.lampinen.log4j2test.Test was created with the message factory org.apache.logging.log4j.message.ReusableMessageFactory@49d904ec and is now requested with a null message factory (defaults to org.apache.logging.log4j.message.ParameterizedMessageFactory), which may create log events with unexpected formatting.
ERROR - Hello world!
```

## Reproduction

See above

**Comment by vy** [comment] 2024-09-09 20:05
@arlampin, thanks so much for the report and the analysis, much appreciated! :bow: I will take care of this issue and make sure that it is fixed with the upcoming `2.24.1`, which we expect to release in ~2 weeks.

**Comment by lauredogit** [comment] 2024-09-13 13:25
Hello,

We also upgraded from 2.23.1 to 2.24.0 and have the same warning.

Unfortunately, this is not just a warning and a false-positvie as with 2.6.0, this actually leads to logs having the wrong formattings...

**Comment by lauredogit** [comment] 2024-09-13 14:47
This happening in environments with some load.

I could not reproduce it locally at this stage.

We are still investigating.

This is a Web application (single Web application in its application server), with hundreds of log files in different formats.

With 2.24.0, some formats are mixed up (e.g. JSON logs are in plain text format).

Most of our loggers are obtained with
```
private static final Logger LOG = LogManager.getLogger(SomeClass.class);
```
Some are obtained via
```
static final Logger LOG = LogManager.getContext(SomeClass.class.getClassLoader(), false).getLogger("some.package.some.id");
```
We do have a custom org.apache.logging.log4j.core.layout.AbstractStringLayout for our JSON logs.

Logs were fine with 2.23.0 and 2.23.1 (for months in production under heavy load).

I'll post more when we have more information or a reproducer.

**Comment by lauredogit** [comment] 2024-09-13 15:25
As far as I can see at the moment, our issue seems to come from the new usage of _org.apache.logging.log4j.core.impl.MementoMessage_.

We should be able to fix that at our end (TBC).

**Comment by lauredogit** [comment] 2024-09-13 15:43
Ok, we assumed _wrongly_ in our custom Layout that we would always receive _ObjectMessage_ instances.

With 2.24.0, we are now getting _MementoMessage_ instances, hence our issue.

We will fix our custom Layout and the issue will be gone for us.

We will also not presume anymore that we will obtain given Message types and only use the contract in the _Message_ interface.

The warning could well be a false-positive as in 2.6...

**Comment by lauredogit** [comment] 2024-09-13 16:16
Sure. 

All our events are already following a JSON structure which does not rely on Jackson and is independent of Log4J.

We don't want to duplicate the whole JSON structures in our log4j configurations, as they are managed by our own logic in the application.

JSON is not the only structure we provide to various ingesters and the structures have to match in the different formats.

Now, with 2.24.0, things might have changed and we might need a brand new stresstest campaign.

The JsonTemplateLayout seems quite powerful, though.

**Closed** 2024-09-16 11:15 UTC
Labels: bug, api, waiting-for-maintainer
