### ISSUE TITLE
Log file stopped rotating daily since I updated to 2.19.0

### ISSUE THREAD

**Issue by SK-Yang** [apache/logging-log4j2#1269] opened 2023-02-07 10:45 UTC
I was using 2,17.0 with log4j-1.2-api 2.17.0 to read my external log4j.properties file and everything went well. But since those deserialization issues appeared last year, I have updated them to 2.19.0, then I noticed my log file stopped rotating daily and keep everything in one since the update. I tried to restart the jvm and nothing change, so I think it might be the log4j's issue.

## Configuration

Version: 2.19.0

Operating system: Win server 2019 

JDK: openjdk version "1.8.0_171-1-redhat"

**Comment by ppkarwasz** [comment] 2023-02-07 14:14
@SK-Yang,

Can you add the contents of your `log4j.properties` file to your question? Since version 2.17.0, `log4j-1.2-api` has changed a lot. For example the builder for `org.apache.log4j.RollingFileAppender` configured a time-based rotation instead of a size-based one (cf. #710).

**Comment by SK-Yang** [comment] 2023-02-12 17:13
@ppkarwasz 
Hi, may I ask if you see anything wrong about the `DailyRollingFileAppender`? or my settings?

**Comment by ppkarwasz** [comment] 2023-02-12 18:41
@SK-Yang,

Your configuration works correctly, but the logger name "com.Common.model.Log4jAP" seems suspicious (if `Common` is a package name, it should be lowercase `common`).

**Comment by SK-Yang** [comment] 2023-02-13 03:14
@ppkarwasz 
> "com.Common.model.Log4jAP" seems suspicious
Yes, it's package name. Somehow the top guys made rules to name like this long time ago.

Hmmm, so my config should be working properly but it isn't... I have enabled log4j's root logger, and it printed this line in log

`log4j:ERROR Failed to rename [D:/Handler_AP/log/AP/AP_Log.log] to [D:/Handler_AP/log/AP/AP_Log.log.2023-02-11]`

Is this a bug like this?
https://bz.apache.org/bugzilla/show_bug.cgi?id=29726

**Comment by ppkarwasz** [comment] 2023-02-13 07:40
@SK-Yang,

Messages prefixed by `log4j:` were used by the unsupported Log4j 1.2. Make sure that:

 * You **don't** have [`log4j:log4j`](https://mvnrepository.com/artifact/log4j/log4j) on your classpath,
 * You have [`org.apache.logging:log4j-1.2-api`](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-1.2-api) on your classpath,
 * Either the system property `log4j1.compatibility=true` is set or `log4j.configuration` points to your `log4j.properties` file.

**Comment by SK-Yang** [comment] 2023-02-13 08:23
@ppkarwasz 
> @SK-Yang,
> 
> Messages prefixed by `log4j:` were used by the unsupported Log4j 1.2. Make sure that:
> 
>     * You **don't** have [`log4j:log4j`](https://mvnrepository.com/artifact/log4j/log4j) on your classpath,
 
I have checked its lib folder, POM, and IDE build path, no old Log4j 1.2 included.

>     * You have [`org.apache.logging:log4j-1.2-api`](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-1.2-api) on your classpath,

log4j-1.2-api-2.19.0.jar, log4j-api-2.19.0.jar, log4j-core-2.19.0.jar. just them.
 
>     * Either the system property `log4j1.compatibility=true` is set or `log4j.configuration` points to your `log4j.properties` file.

doesn't have any system prop setting inside my program, but I do have a simple mechanism to read my properties file.

```
public class Log4j {

	public final static Logger LOG = Logger.getLogger(Log4j.class);
	private static boolean configurated = false;

	public Log4j() {
	};

	public Log4j(String config_path) {
		if (configurated == false) {
			Properties p = new Properties();

			try {
				p.load(new FileInputStream(config_path));
				PropertyConfigurator.configure(p);
				configurated = true;
			} catch (IOException e) {
				System.out.println("[Error] Unable to read log4j config: " + e.getMessage());
			} finally {
				if (p != null) {
					p.clear();
				}
			}
		}
	};
}
```
This works fine since 1.12.x to 2.17.0 over the past few years. I still cannot understand why it won't on 2.19.0.

**Comment by ppkarwasz** [comment] 2023-02-13 21:14
`PropertyConfigurator#configure()` was a no-op before version 2.17.2 (cf. [source code](https://github.com/apache/logging-log4j2/blob/rel/2.17.1/log4j-1.2-api/src/main/java/org/apache/log4j/PropertyConfigurator.java)). Another mechanism must be configuring your logging system.

**Comment by ppkarwasz** [comment] 2023-10-26 06:31
I am closing this since it can not be reproduced and it probably concerns Log4j 1.x/Reload4j.

Feel free to reopen it if there is new data.

**Closed by ppkarwasz** 2023-10-26 06:31 UTC
Labels: bug, configuration, unconfirmed
