### ISSUE TITLE
Logging a java.sql.Date fails with java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by ialmandoz** [apache/logging-log4j2#1497] opened 2023-05-31 14:26 UTC
## Description

Logging a java.sql.Date fails with java.lang.UnsupportedOperationException and statements are not logged.
This worked ok with 2.17.2

## Configuration

**Version:** 2.20.0

**Operating system:** Windows

**JDK:** 1.8

## Logs

```
`Caused by: java.lang.UnsupportedOperationException
        at java.sql.Date.toInstant(Date.java:304) ~[?:1.8.0_201]
        at org.apache.logging.log4j.message.ParameterFormatter.appendDate(ParameterFormatter.java:492) ~[log4j-api-2.20.0.jar:2.20.0]
        at org.apache.logging.log4j.message.ParameterFormatter.appendSpecialTypes(ParameterFormatter.java:485) ~[log4j-api-2.20.0.jar:2.20.0]
        at org.apache.logging.log4j.message.ParameterFormatter.recursiveDeepToString(ParameterFormatter.java:474) ~[log4j-api-2.20.0.jar:2.20.0]
        at org.apache.logging.log4j.message.ParameterFormatter.recursiveDeepToString(ParameterFormatter.java:449) ~[log4j-api-2.20.0.jar:2.20.0]
        at org.apache.logging.log4j.message.ParameterFormatter.formatMessage2(ParameterFormatter.java:192) ~[log4j-api-2.20.0.jar:2.20.0]
        at org.apache.logging.log4j.message.ParameterizedMessage.formatTo(ParameterizedMessage.java:227) ~[log4j-api-2.20.0.jar:2.20.0]
`
```

## Reproduction

log4j2.xml
```

<Configuration status="WARN">
  <Appenders>
    <Console name="CONSOLE" target="SYSTEM_OUT">
        <PatternLayout pattern="%d [%t] %-5p %c{2} %x - %m%n"/>
    </Console>
  </Appenders>
  <Loggers>
    <Root level="debug">
      <AppenderRef ref="CONSOLE" />
    </Root>
  </Loggers>
</Configuration>

```
Code

```
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class Log4j2SqlDateError {

    private static final Logger logger = LogManager.getLogger(Log4j2SqlDateError.class);
    
    public static void main(String[] args) throws Exception {
        java.sql.Date date = new java.sql.Date(System.currentTimeMillis());
        logger.error("Message {}", date);
    }
}
```

**Comment by ppkarwasz** [comment] 2023-05-31 14:48
This is a duplicate of #1366.

**Closed by ppkarwasz** 2023-05-31 14:48 UTC
