### ISSUE TITLE
[2.17.1] AsyncLogger thread is stuck on 100% CPU on lmax-34. queue polling

### ISSUE THREAD

**Issue by shloim** [apache/logging-log4j2#2169] opened 2024-01-07 14:49 UTC
## Description
Some low probability race condition causes lmax to loop indefinitely on Thread.yield

## Configuration

-DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector
-Dlog4j2.enable.threadlocals=true
-Dlog4j2.enable.direct.encoders=true
-XX:CompileCommand=dontinline,org.apache.logging.log4j.core.async.perftest.NoOpIdleStrategy::idle

**Version:** 2.17.1

**Operating system:** Centos 8

**JDK:** OpenJDK 64-Bit Server VM GraalVM LIBGRAAL 20.3.3 (build 11.0.12+5-jvmci-20.3-b06)

## Logs
It would seem that the queue datastructure becomes corrupted and cas=uses the polling thread to loop infinitely with the following stacktrace:
```
"Log4j2-TF-1-AsyncLogger[AsyncContext@46f5f779]-1" #18 daemon prio=5 os_prio=0 cpu=4404755.82ms elapsed=4733.22s tid=0x00007fed7ade9800 nid=0xcd runnable  [0x00007fed7bffd000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.Thread.yield(java.base@11.0.12/Native Method)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.transferAfterCancelledWait(java.base@11.0.12/AbstractQueuedSynchronizer.java:1752)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@11.0.12/AbstractQueuedSynchronizer.java:2119)
        at com.lmax.disruptor.TimeoutBlockingWaitStrategy.waitFor(TimeoutBlockingWaitStrategy.java:38)
        at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
        at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:159)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
        at java.lang.Thread.run(java.base@11.0.12/Thread.java:829)
```

## Reproduction
This was found on a large production system with very low probability. Using log4j with the above settings. We don't know the exact case where the polling thread reaches this state

**Comment by vy** [comment] 2024-01-08 08:09
@shloim, the upcoming Log4j 2 release (i.e., `2.23.0`) will be the very first Log4j 2 version that ships Disruptor 4 support. (Disruptor 3 will still work too.) Is that something you can try?

**Comment by ppkarwasz** [comment] 2024-01-08 08:19
Alternatively, can you upgrade your Log4j version to 2.18.0 or later?

In 2.18.0 @remkop backported the `TimeoutBlockingWaitStrategy` from Disruptor 4.x with such a comment:

https://github.com/apache/logging-log4j2/blob/252f1a65e1b44fa78c622b4140d9116bf57d3617/log4j-core/src/main/java/org/apache/logging/log4j/core/async/TimeoutBlockingWaitStrategy.java#L34-L40

The difference in the locking mechanism seems relevant to your case.

**Comment by shloim** [comment] 2024-01-08 12:26
> Alternatively, can you upgrade your Log4j version to 2.18.0 or later?
> 
> In 2.18.0 @remkop backported the `TimeoutBlockingWaitStrategy` from Disruptor 4.x

I'm working on testing it with log4j=2.22.1 slf4j=1.7.36 lmax=3.4.4

**Comment by shloim** [comment] 2024-01-08 13:25
> Alternatively, can you upgrade your Log4j version to 2.18.0 or later?
> 
> In 2.18.0 @remkop backported the `TimeoutBlockingWaitStrategy` from Disruptor 4.x with such a comment:
> 
> https://github.com/apache/logging-log4j2/blob/252f1a65e1b44fa78c622b4140d9116bf57d3617/log4j-core/src/main/java/org/apache/logging/log4j/core/async/TimeoutBlockingWaitStrategy.java#L34-L40
> 
> The difference in the locking mechanism seems relevant to your case.

Do I need to set a custom WaitStrategy or can I keep the default behavior?

**Comment by ppkarwasz** [comment] 2024-01-08 14:07
@shloim,

"Our" `TimeoutBlockingWaitStrategy` should be the default one.

**Comment by shloim** [comment] 2024-01-14 12:58
After switching to log4j 2.18.0 the issue persists but in a different stacktrace:

```
"Log4j2-TF-1-AsyncLogger[AsyncContext@46f5f779]-1" #20 daemon prio=5 os_prio=0 cpu=3228328.37ms elapsed=3495.56s tid=0x00007fea233e9000 nid=0xd0 runnable  [0x00007fea23dfd000]
   java.lang.Thread.State: RUNNABLE
        at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:159)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
        at java.lang.Thread.run(java.base@11.0.12/Thread.java:829)
```

**Comment by vy** [comment] 2024-01-14 19:41
@shloim, can you give `2.23.0-SNAPSHOT` a try in combination with Disruptor 4? (See [docs on how to configure Maven/Gradle/SBT for snapshot builds](https://logging.apache.org/log4j/2.x/maven-artifacts.html#snapshot-builds).)

**Comment by AndreKurait** [comment] 2024-05-04 04:52
Hi,
I'm seeing this with 2.23.1 and Disruptor 4.0.0 in my application.

It's happening when i use
```

**Comment by vy** [comment] 2024-05-06 09:29
> Perhaps the [Log4j async manual](https://logging.apache.org/log4j/2.x/manual/async.html) could be more clear 

We can indeed do this. Updated the #2534 description accordingly.

**Comment by ppkarwasz** [comment] 2024-05-21 20:58
The documentation of `Yield` was fixed in #2577 .

**Closed by ppkarwasz** 2024-05-21 20:58 UTC
Labels: bug, async, waiting-for-user

**Comment by Baixiu-code** [comment] 2024-11-06 10:16
same issues. and cpu 100%. and t version is 3.4.2 .
![image](https://github.com/user-attachments/assets/ad3f636b-b84c-458b-b109-374a6258e2c7)

**Comment by ppkarwasz** [comment] 2024-11-06 11:05
@Baixiu-code,

- Are you using Log4j Core `2.24.1`?
- Did you try using `com.lmax:disruptor` version `4.0.0`?
- What is the status of the **polling** thread? The polling thread's name starts with `Log4j2-TF-<number>-AsyncLogger` as showed in the [initial comment for this issue](#issue-2069159269). Your screenshot only covers the logging threads, which are blocked, because the queue is full. Can you provide the stack trace of the polling thread as **text** instead of an image?

**Comment by five111** [comment] 2026-03-18 08:53
hi guys,It seems I have encountered the same problem.
this is my thread dump
`
"Log4j2-TF-1-AsyncLogger[AsyncContext@421faab1]-1" Id=19 cpuUsage=97.45% deltaTime=195ms time=158786877ms RUNNABLE
    at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java)
    at com.lmax.disruptor.BatchEventProcessor.processEvents(Unknown Source)
    at com.lmax.disruptor.BatchEventProcessor.run(Unknown Source)
    at java.base@21.0.10/java.lang.Thread.runWith(Unknown Source)
    at java.base@21.0.10/java.lang.Thread.run(Unknown Source)

"Log4j2-TF-1-AsyncLogger[AsyncContext@421faab1]-1" Id=19 cpuUsage=99.03% deltaTime=198ms time=158791970ms RUNNABLE
    at com.lmax.disruptor.BatchEventProcessor.processEvents(Unknown Source)
    at com.lmax.disruptor.BatchEventProcessor.run(Unknown Source)
    at java.base@21.0.10/java.lang.Thread.runWith(Unknown Source)
    at java.base@21.0.10/java.lang.Thread.run(Unknown Source)

`
this is my env

- log4j core version 2.25.3
- com.lmax:disruptor 4.0.0
- java version 21

i dont konw why,  help please

**Comment by ppkarwasz** [comment] 2026-03-19 07:39
Which `WaitStrategy` are you using? As [documented here](https://logging.apache.org/log4j/2.x/manual/async.html#log4j2.asyncLoggerWaitStrategy), some wait strategies will use 100% CPU by design.

**Comment by five111** [comment] 2026-03-19 08:06
timeout
