### ISSUE TITLE
jlink / log4j2 2.21.1

### ISSUE THREAD

**Issue by CodeDead** [apache/logging-log4j2#1896] opened 2023-10-23 23:41 UTC
## Description

Without using any log4j2 plugins and after upgrading to log4j 2.21.0 or 2.21.1 I am having issues bundling log4j2-core with my jlink'd build. I think this has something to do with an incorrect dependency being set in the module-info file introduced in log4j2 2.21.0

## Configuration

**Version:** 2.21.0, 2.21.1

**Operating system:** Windows 10, Windows 11, Fedora Linux 38

**JDK:** 17 - 21

## Logs

Directly from jlink:
```
Error: Module org.apache.logging.log4j.core does not read a module that exports javax.annotation.processing
```

## Reproduction

Try a jlink build. Not using any log4j2 plugins.

**Comment by ppkarwasz** [comment] 2023-10-24 06:20
@CodeDead,

The problem seems to come from the fact that `log4j-core` contains an annotation processor:
```
provides javax.annotation.processing.Processor with org.apache.logging.log4j.core.config.plugins.processor.PluginProcessor
```
The processor itself depends on the `java.compiler` module, which is optional:
```
requires static java.compiler
```

We should probably remove `static` from the `java.compiler` module. @jvz, @vy, what do you think?

You can easily work around this problem, by adding `--add-modules java.compiler` to the `jlink` invocation.

**Remark:** Even if we solve this problem, `jlink` complains about `log4j-api`:
```
[ERROR] Error: java.lang.RuntimeException: Module org.apache.logging.log4j's descriptor indicates the set of packages is : [org.apache.logging.log4j.status, org.apache.logging.log4j.message, org.apache.logging.log4j.util, org.apache.logging.log4j.simple, org.apache.logging.log4j, org.apache.logging.log4j.internal, org.apache.logging.log4j.spi], but module contains packages: [org.apache.logging.log4j.status, org.apache.logging.log4j, org.apache.logging.log4j.util.internal, org.apache.logging.log4j.internal, org.apache.logging.log4j.spi, org.apache.logging.log4j.util, org.apache.logging.log4j.message, org.apache.logging.log4j.simple]
```
In this case the problem is that `META-INF/versions/9` contains a new package (`org.apache.logging.log4j.util.internal`), which is not present in the Java 8 version.

**Comment by ppkarwasz** [comment] 2023-10-24 07:49
I am marking this as a feature request, since with the previous versions of `log4j-core` JLink failed with:
```
[ERROR] Error: automatic module cannot be used with jlink: org.apache.logging.log4j.core from file:///home/piotr/.m2/repository/org/apache/logging/log4j/log4j-core/2.20.0/log4j-core-2.20.0.jar
```

**Comment by vy** [comment] 2023-10-24 09:22
@CodeDead, could you provide us a simple (the simplest possible, please!) instruction set to reproduce your issue? Such that we can validate it indeed worked against `2.20.0` and got broken in `2.21.0`.

**Comment by ppkarwasz** [comment] 2023-10-24 09:31
I created a sample custom JRE built in:

https://github.com/apache/logging-log4j-samples/tree/main/log4j-samples-jlink

**Comment by CodeDead** [comment] 2023-10-24 09:44
@vy @ppkarwasz 

Sample using gradle and log4j2 2.20.0
https://github.com/CodeDead/sample-log4j2

It is sufficient to run the jlink task in Gradle.

**Comment by vy** [comment] 2023-10-25 09:42
@CodeDead, thank you so much for taking time to provide `sample-log4j2`! :heart_eyes: It certainly helped for troubleshooting!

I have pushed ca225f0e7a442c5646351a2042a7721f2921b740 addressing your issue, [the build](https://github.com/apache/logging-log4j2/actions/runs/6638069559) should have successfully completed as you read this. This `2.22.0-SNAPSHOT` version works against the `sample-log4j2` where the `forceMerge('log4j-api')` line and the `mergedModule { ... }` block in `build.gradle` is commented out – I don't think you should be needing/doing any of these.

```
$ git diff
warning: CRLF will be replaced by LF in gradlew.bat.
The file will have its original line endings in your working directory
diff --git a/build.gradle b/build.gradle
index a703f21..22e113f 100644
--- a/build.gradle
+++ b/build.gradle
@@ -21,28 +21,28 @@ java {
 
 jlink {
     options = ['--strip-debug', '--compress', 'zip-9', '--no-header-files', '--no-man-pages']
-    forceMerge('log4j-api')
+    // forceMerge('log4j-api')
     launcher {
         name = 'Sample'
     }
 
-    mergedModule {
-        additive = true
-        uses 'org.apache.logging.log4j.util.PropertySource'
-        uses 'org.apache.logging.log4j.core.util.ContextDataProvider'
-        uses 'org.apache.logging.log4j.core.util.WatchEventService'
-        uses 'org.apache.logging.log4j.spi.Provider'
-        uses 'org.apache.logging.log4j.message.ThreadDumpMessage.ThreadInfoFactory'
-    }
+    // mergedModule {
+    //     additive = true
+    //     uses 'org.apache.logging.log4j.util.PropertySource'
+    //     uses 'org.apache.logging.log4j.core.util.ContextDataProvider'
+    //     uses 'org.apache.logging.log4j.core.util.WatchEventService'
+    //     uses 'org.apache.logging.log4j.spi.Provider'
+    //     uses 'org.apache.logging.log4j.message.ThreadDumpMessage.ThreadInfoFactory'
+    // }
 }
 
-
 repositories {
+    mavenLocal()
     mavenCentral()
 }
 
 dependencies {
-    implementation 'org.apache.logging.log4j:log4j-core:2.20.0'
+    implementation 'org.apache.logging.log4j:log4j-core:2.22.0-SNAPSHOT'
     testImplementation platform('org.junit:junit-bom:5.9.1')
     testImplementation 'org.junit.jupiter:junit-jupiter'
 }
$ ./gradlew jlink
$ build/image/bin/java -m sample.log4j.main
WARN StatusConsoleListener JNDI lookup class is not available because this JRE does not support JNDI. JNDI string lookups will not be available, continuing configuration. Ignoring java.lang.NoClassDefFoundError: javax/naming/Context
[INFO][2023-10-25 11:40:21.301][main] Main	-	Hello, World!
```

I'd appreciate it if you can close the ticket if your problem is resolved.

**Comment by CodeDead** [comment] 2023-10-25 10:20
Hi @vy ,

Thanks for the quick response! The removal of the forced mergeModule and forceMerge blocks and it running and compiling would indicate that indeed, log4j-core:2.22.0-SNAPSHOT has the right module configuration for proper jlink-ing this build.

Thank you for hard work!

**Comment by vy** [comment] 2023-10-25 11:43
@CodeDead, thanks so much for the report and the help with diagnosis. :bow: I am closing the ticket per your approval.

**Closed by vy** 2023-10-25 11:43 UTC
Labels: bug, jpms
