### ISSUE TITLE
Log4j writes certain errors to System.out instead of System.err

### ISSUE THREAD

**Issue by hblohm** [apache/logging-log4j2#1484] opened 2023-05-23 16:17 UTC
When using log4j (tried 2.17.0 and 2.20.0) it initializes StackLocator that writes a warning to System.out when not finding sun.reflect.Reflection.getCallerClass - which is true for Java versions >= 9 I believe.

This pretty much invalidates the use of log4j in a java command line that produces binary output that gets stream for further processing. While text output could possibly be suitably filtered, for binary output that is really unusable.

It would be great, if that output could be dropped or at least sent to System.err (like regular log output). 

Any workaround would be greatly appreciated!

Thanks,
Henning

**Comment by ppkarwasz** [comment] 2023-05-23 17:28
@hblohm,

The particular warning you are having is most probably due to an incorrect repackaging of Log4j libraries. The Log4j API is a multi-release library, which contains both a version for Java 8 and Java 9+. If you are using Maven Shade plugin use a configuration like in [this answer](https://github.com/apache/logging-log4j2/issues/1386#issuecomment-1481686029).

Regarding you general remark I agree: we shouldn't **ever** log errors to `System.out`, but use `LowLevelLogUtil` or `StatusLogger`, whichever is available.

**Comment by hblohm** [comment] 2023-05-24 05:37
@ppkarwasz 

Thank you for that swift reply! With respect to Log4J, my setup includes dependencies

```xml
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <!-- Log4j 1.x bridge API -->
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-1.2-api</artifactId>
            <version>${log4j.version}</version>
        </dependency>
```

and the only log4j libraries I see in use are log4j-1.2-api-2.20.0.jar, log4j-api-2.20.0.jar, and log4j-core-2.20.0.jar. StackLocator can be found in log4j-api-2.20.0.jar. So I guess I cannot really do without it. 

I will look for some workaround via writing to intermediate local files - so that this is not a blocker for me.

**Comment by ppkarwasz** [comment] 2023-05-24 06:20
@hblohm,

The "workaround" is to prevent the _"WARNING: `sun.reflect.Reflection.getCallerClass` is not supported. This will impact performance."_ from appearing **at all**.

As I mentioned earlier this is a problem due to the [multi-release](https://www.baeldung.com/java-multi-release-jar) nature of `log4j-api`. This usually appears if:
 * either you deploy your application as a so-call fat-jar (or uber-jar): you copy the contents of all dependency jars into a single jar. If this is the case, look at the Maven configuration I [proposed here](https://github.com/apache/logging-log4j2/issues/1386#issuecomment-1481686029), which solves two other problems related to fat-jars,
 * or you use a classloader that does not support multi-release jars. The classloaders in JRE 9+ all support multi-release, but e.g. Tomcat's classloader didn't support it until version 8.5.24 (late 2017).  Other projects implemented multi-release support around that same time.

**Comment by hblohm** [comment] 2023-05-24 06:32
Thank you. Now I get it. Yes, could be the classloader.

**Comment by FeldrinH** [comment] 2023-06-16 16:20
I wanted to point out that this is particularly problematic if stdout is used for structured communication for example via JSON-RPC. I spent several hours trying to figure out why a change to some logging statements silently breaks a VS Code extension that communicates over stdout using JSON-RPC and this warning turned out to be the cause.

**Comment by FeldrinH** [comment] 2023-06-16 16:54
It would be nice if these warnings could be printed to System.err instead so future developers that happen to encounter this issue don't waste time like I did.

**Comment by vy** [comment] 2023-10-05 12:13
@hblohm, thanks so much for the report, much appreciated! :bow: Landed a fix replacing `System.out` with `System.err`.

**Closed by vy** 2023-10-05 12:13 UTC
Labels: bug
