### ISSUE TITLE
`ParameterFormatter.appendDate` causes an `UnsupportedOperationException` with a `java.sql.Date`

### ISSUE THREAD

**Issue by gtoison** [apache/logging-log4j2#1476] opened 2023-05-11 08:04 UTC
## Description

`ParameterFormatter.appendDate` causes an `UnsupportedOperationException` when trying to call `java.sql.Date.toInstant()`

## Configuration

**Version:** 2.20.0

**Operating system:** W10

**JDK:** JDK temurin 20

## Logs

```
ERROR StatusConsoleListener An exception occurred processing Appender Console
 java.lang.UnsupportedOperationException
	at java.sql/java.sql.Date.toInstant(Date.java:316)
	at org.apache.logging.log4j.message.ParameterFormatter.appendDate(ParameterFormatter.java:492)
	at org.apache.logging.log4j.message.ParameterFormatter.appendSpecialTypes(ParameterFormatter.java:485)
	at org.apache.logging.log4j.message.ParameterFormatter.recursiveDeepToString(ParameterFormatter.java:474)
	at org.apache.logging.log4j.message.ParameterFormatter.appendMap(ParameterFormatter.java:589)
	at org.apache.logging.log4j.message.ParameterFormatter.appendPotentiallyRecursiveValue(ParameterFormatter.java:511)
	at org.apache.logging.log4j.message.ParameterFormatter.recursiveDeepToString(ParameterFormatter.java:478)
	at org.apache.logging.log4j.message.ParameterFormatter.appendArray(ParameterFormatter.java:557)
	at org.apache.logging.log4j.message.ParameterFormatter.appendPotentiallyRecursiveValue(ParameterFormatter.java:509)
	at org.apache.logging.log4j.message.ParameterFormatter.recursiveDeepToString(ParameterFormatter.java:478)
	at org.apache.logging.log4j.message.ParameterFormatter.recursiveDeepToString(ParameterFormatter.java:449)
	at org.apache.logging.log4j.message.ParameterFormatter.formatMessage2(ParameterFormatter.java:192)
	at org.apache.logging.log4j.message.ParameterizedMessage.formatTo(ParameterizedMessage.java:227)
	at org.apache.logging.log4j.core.pattern.MessagePatternConverter$SimpleMessagePatternConverter.format(MessagePatternConverter.java:121)
	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:44)
	at org.apache.logging.log4j.core.layout.PatternLayout$PatternFormatterPatternSerializer.toSerializable(PatternLayout.java:384)
	at org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:240)
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:225)
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:59)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:215)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:208)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:199)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:683)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:641)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:624)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:560)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
	at org.apache.logging.log4j.core.Logger.log(Logger.java:163)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2168)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2122)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2105)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2015)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1886)
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:849)
```

## Reproduction

			List list = Collections.singletonList(java.sql.Date.valueOf("2023-5-11"));
			LOGGER.error("Test {}", list, new Exception());

**Comment by ppkarwasz** [comment] 2023-05-11 12:00
@gtoison,

Thank you for your report. The issue is known (#1366) and fixed in the snapshots.

If the snapshots don't solve your problem, please reopen the issue.

**Closed as completed by ppkarwasz** 2023-05-11 12:00 UTC

**Comment by kgregory-chariot** [comment] 2023-12-05 14:09
@ppkarwasz - I believe that #1366 referenced a different issue -- or `ParameterFormatter.appendDate()` is dead code and should be removed.

This is the [current mainline code](https://github.com/apache/logging-log4j2/blob/2.x/log4j-api/src/main/java/org/apache/logging/log4j/message/ParameterFormatter.java#L434C28-L434C38):

```
    private static boolean appendDate(final Object o, final StringBuilder str) {
        if (!(o instanceof Date)) {
            return false;
        }
        str.append(DATE_FORMATTER.format(((Date) o).toInstant()));
        return true;
    }
```

If you pass an instance of `java.sql.Date` (or `java.sql.Time`) to this function, it will throw `UnsupportedOperationException` [per documentation](https://docs.oracle.com/en/java/javase/21/docs/api/java.sql/java/sql/Date.html#toInstant()).

To properly handle the `java.sql` types, you could either add some more instance-of tests to perform valid conversions, or do the following:

```
str.append(DATE_FORMATTER.format(Instant.ofEpochMilli(((Date) o).getTime())));
```

I actually think that the additional instance-of tests would be better, using the built-in string conversion, because treating a SQL date or time as a timestamp will be confusing.

**Comment by ppkarwasz** [comment] 2023-12-05 14:28
Hi @kgregory-chariot,

The only usage of the **private** method `appendDate` is:

```java
    private static boolean appendSpecialTypes(final Object o, final StringBuilder str) {
        return StringBuilders.appendSpecificTypes(str, o) || appendDate(o, str);
    }
```

The `StringBuilders.appendSpecificTypes` call deals with `java.sql.Date` and `java.sql.Time` the way you suggest: it calls `Object#toString()`.
