### ISSUE TITLE
XSD Schema missing LoggerConfig.additivity

### ISSUE THREAD

**Issue by vertx-one** [apache/logging-log4j2#3313] opened 2024-12-20 09:41 UTC
## Description

Documentaion page describe additivity available at Logger: https://logging.apache.org/log4j/2.x/manual/configuration.html#logger-attributes-additivity

https://logging.apache.org/xml/ns/log4j-config-2.xsd provides schema with content

```xml
...
<complexType name="org.apache.logging.log4j.core.config.LoggerConfig">
<annotation>
<documentation>Logger object that is created via configuration.</documentation>
</annotation>
<sequence>
<group ref="log4j:org.apache.logging.log4j.core.Filter" minOccurs="0"/>
<element name="AppenderRef" type="log4j:org.apache.logging.log4j.core.config.AppenderRef" minOccurs="0" maxOccurs="unbounded"/>
<element name="Property" type="log4j:org.apache.logging.log4j.core.config.Property" minOccurs="0" maxOccurs="unbounded"/>
</sequence>
<attribute name="includeLocation" type="string"/>
<attribute name="level" type="log4j:org.apache.logging.log4j.Level"/>
<attribute name="levelAndRefs" type="string"/>
<attribute name="name" type="string"/>
</complexType>
...
<complexType name="org.apache.logging.log4j.core.config.LoggerConfig.RootLogger">
<annotation>
<documentation>The root Logger.</documentation>
</annotation>
<sequence>
<group ref="log4j:org.apache.logging.log4j.core.Filter" minOccurs="0"/>
<element name="AppenderRef" type="log4j:org.apache.logging.log4j.core.config.AppenderRef" minOccurs="0" maxOccurs="unbounded"/>
<element name="Property" type="log4j:org.apache.logging.log4j.core.config.Property" minOccurs="0" maxOccurs="unbounded"/>
</sequence>
<attribute name="additivity" type="boolean"/>
<attribute name="includeLocation" type="string"/>
<attribute name="level" type="log4j:org.apache.logging.log4j.Level"/>
<attribute name="levelAndRefs" type="string"/>
</complexType>
...
```

`<attribute name="additivity" type="boolean"/>` missed at type org.apache.logging.log4j.core.config.LoggerConfig

As result in IDEA: 
![image](https://github.com/user-attachments/assets/1b97f260-60b2-4ab7-ac4f-90ca36fb47ad)

## Configuration

**Version:** 2.x

**Operating system:** linux, any

**JDK:** 17

## Logs

```
[Stacktraces, errors, etc. relevant applications logs.]
```

## Reproduction

[An isolated test reproducing the test.
JUnit tests similar to the ones in the code base are extremely appreciated.]

**Comment by ppkarwasz** [comment] 2024-12-20 10:05
@vertx-one,

Thanks for the report. I am closing it as duplicate of apache/logging-log4j-tools#135.

**Closed by ppkarwasz** 2024-12-20 10:05 UTC
Labels: waiting-for-maintainer
